[package]
name = "nebula-graph-demo-tokio"
version = "0.1.0"
authors = ["vkill <vkill.net@gmail.com>"]
edition = "2018"

[[bin]]
name = "bb8_graph_pool"
path = "src/bb8_graph_pool.rs"

[[bin]]
name = "graph_client"
path = "src/graph_client.rs"

[[bin]]
name = "v2_bb8_graph_pool"
path = "src/v2_bb8_graph_pool.rs"

[[bin]]
name = "v2_graph_client"
path = "src/v2_graph_client.rs"

[dependencies]
# non-pool
nebula-graph-client = { path = "../../nebula-graph-client", version = "0.2" }
fbthrift-transport = { version = "0.3", features = ["tokio_io"] }

# bb8
bb8 = "0.4"
bb8-nebula-graph = { path = "../../bb8-nebula-graph", version = "0.4" }

# common
tokio = { version = "0.2", default-features = false, features = ["io-util", "net", "macros"] }
